---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubermaster
  name: kubermaster-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubermaster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubermaster
    spec:
      serviceAccount: kubermaster
      containers:
      - env:
        - name: TOKEN
          value: "token here"
        - name: ENV
          value: staging
        - name: NEWRELIC_KEY
          value: ""
        image: "stevelacy/kubermaster:ba53225"
        imagePullPolicy: Always
        name: kubermaster
        ports:
        - containerPort: 9090
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kubermaster
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: kubermaster
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubermaster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kubermaster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubermaster-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubermaster
  apiGroup: ""
  namespace: default
roleRef:
  kind: Role
  name: kubermaster-role
  apiGroup: ""
---
